version: '3.8'

services:
  api:
    build: .
    container_name: task-manager-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/instance/task_manager.db
    restart: always
